# diag-colorwheel.ps1 - verify the colour wheel's maths WITHOUT touching the keyboard.
#
# The wheel is only trustworthy if the pixel that is drawn at (x,y) is the colour that
# clicking (x,y) produces. Both sides are generated by ClevoHelper.ColorWheel, but by two
# different code paths (Pixels() for drawing, Pick() for clicking), so this script compares
# them pixel by pixel instead of assuming they agree.
#
# Also checks the three cardinal hues, the centre (which must be white) and the outside
# (which must be transparent / unpickable).
#
# Usage: powershell -STA -NoProfile -ExecutionPolicy Bypass -File diag-colorwheel.ps1
[CmdletBinding()]
param([int]$Size = 150)

$ErrorActionPreference = 'Stop'
$src = Join-Path $PSScriptRoot 'ClevoHelper.ps1'
# the wheel helper lives in the panel script; pull in just that block (dot-sourcing the whole
# panel would open a window)
$txt = Get-Content -Raw -LiteralPath $src
$start = $txt.IndexOf("if (-not ('ClevoHelper.ColorWheel' -as [type]))")
$end = $txt.IndexOf('# Volume rows are generated')
if ($start -lt 0 -or $end -lt 0) { throw 'colour-wheel block not found in ClevoHelper.ps1' }
$block = $txt.Substring($start, $end - $start)
# strip the panel-only bitmap builder (needs WPF types the console host may not have loaded)
$block = $block.Substring(0, $block.IndexOf('$script:WheelSize'))
Invoke-Expression $block

$px = [ClevoHelper.ColorWheel]::Pixels($Size)
"pixels: {0} bytes for {1}x{1} (expected {2})" -f $px.Length, $Size, ($Size * $Size * 4)

$fail = 0
function Check([string]$what, [bool]$ok, [string]$detail) {
    if ($ok) { "  [ OK ] {0,-34} {1}" -f $what, $detail } else { "  [FAIL] {0,-34} {1}" -f $what, $detail; $script:fail++ }
}

'--- drawn pixel vs clicked colour (every 10th pixel inside the circle) ---'
$mismatch = 0
$checked = 0
$stride = $Size * 4
for ($y = 0; $y -lt $Size; $y += 10) {
    for ($x = 0; $x -lt $Size; $x += 10) {
        $p = [ClevoHelper.ColorWheel]::Pick($x + 0.5, $y + 0.5, $Size)
        $i = $y * $stride + $x * 4
        if ($null -eq $p) {
            if ($px[$i + 3] -ne 0) { $mismatch++ }        # outside: must be transparent
            continue
        }
        $checked++
        if ($px[$i] -ne $p[2] -or $px[$i + 1] -ne $p[1] -or $px[$i + 2] -ne $p[0] -or $px[$i + 3] -ne 255) {
            $mismatch++
        }
    }
}
Check 'drawn == clicked' ($mismatch -eq 0) ("{0} pixels compared, {1} mismatches" -f $checked, $mismatch)

'--- hue angles ---'
# HSV puts pure red at 0°, pure green at 120° and pure blue at 240°. 90° / 180° / 270° are
# the points BETWEEN those (yellow-green / cyan / violet) - the first version of this test
# asserted "hue 90 must be pure green" and failed against a correct wheel.
$r0 = $Size / 2.0
$cases = @(
    @{ Name = '0° 纯红';    Ang = 0;   Max = 'R' },
    @{ Name = '120° 纯绿';  Ang = 120; Max = 'G' },
    @{ Name = '240° 纯蓝';  Ang = 240; Max = 'B' },
    @{ Name = '90° 黄绿';   Ang = 90;  Max = 'G' },
    @{ Name = '180° 青';    Ang = 180; Max = 'GB' },
    @{ Name = '270° 紫';    Ang = 270; Max = 'B' }
)
foreach ($c in $cases) {
    # walk out from the centre along this angle so the point is inside the circle
    $rad = $c.Ang * [Math]::PI / 180.0
    $x = $r0 + [Math]::Cos($rad) * ($r0 - 3)
    $y = $r0 + [Math]::Sin($rad) * ($r0 - 3)
    $p = [ClevoHelper.ColorWheel]::Pick($x, $y, $Size)
    $rgb = 'R{0,3} G{1,3} B{2,3}  hue={3,3} sat={4}%' -f $p[0], $p[1], $p[2], $p[3], $p[4]
    # the drawn angle must come back as the same hue (2° covers rounding; computed as a
    # circular distance because PowerShell's % keeps the sign of the dividend)
    $d = ((($p[3] - $c.Ang) % 360) + 360) % 360
    if ($d -gt 180) { $d = 360 - $d }
    $hueOk = ($d -le 2)
    $maxOk = switch ($c.Max) {
        'R'  { $p[0] -ge $p[1] -and $p[0] -ge $p[2] -and $p[0] -gt 240 }
        'G'  { $p[1] -ge $p[0] -and $p[1] -ge $p[2] -and $p[1] -gt 240 }
        'B'  { $p[2] -ge $p[0] -and $p[2] -ge $p[1] -and $p[2] -gt 240 }
        'GB' { $p[1] -gt 240 -and $p[2] -gt 240 -and $p[0] -lt 40 }
    }
    Check $c.Name ($hueOk -and $maxOk) $rgb
}

'--- centre and outside ---'
$pc = [ClevoHelper.ColorWheel]::Pick($r0, $r0, $Size)
Check '中心 = 白 (sat 0)' ($pc[0] -gt 250 -and $pc[1] -gt 250 -and $pc[2] -gt 250) ('R{0} G{1} B{2}' -f $pc[0], $pc[1], $pc[2])
$po = [ClevoHelper.ColorWheel]::Pick(-5, -5, $Size)
Check '圆外 = 取不到颜色' ($null -eq $po) ('Pick 返回 ' + $(if ($null -eq $po) { 'null' } else { '非 null' }))

''
if ($fail) { "RESULT: $fail problem(s)"; exit 1 } else { 'RESULT: 色盘绘制与取色完全一致' }
